Use pcsc v2
Coppernic/PcscSample pull request #12
Opened 2023-02-03 08:17 UTC by FlorentYvinec

2023-02-03 13:02 UTC, mcghorayeb approved these changes

2023-02-06 08:30 UTC, mreynier commented on app/src/main/java/fr/coppernic/samples/pcsc/ui/MainActivity.java
> +                    updateSpinner();
Il faudrait le mettre apres le "observeOn" pour que ce soit "updater" sur le main thread non? Tu as pas de crash?

2023-02-06 14:00 UTC, FlorentYvinec commented on app/src/main/java/fr/coppernic/samples/pcsc/ui/MainActivity.java
> +                    updateSpinner();
Alors pas de crash (la fonction appelée doit pouvoir être appellée en dehors du uiMainThread), mais dans l'absolu tu as raison, je corrige

2023-02-06 15:31 UTC, mreynier approved these changes

2023-02-13 15:34 UTC, mreynier requested changes
if core service not installed or not last version -> crash!

2023-02-27 10:21 UTC, merged